server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  client_max_body_size 120m;

  location = /health { access_log off; return 200 'ok'; add_header Content-Type text/plain; }
  location /api/ { proxy_pass http://hubfiscal-api:8080/api/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
  location /docs { proxy_pass http://hubfiscal-api:8080/docs; }
  location /openapi.json { proxy_pass http://hubfiscal-api:8080/openapi.json; }
  location / { try_files $uri $uri/ /index.html; }
}
