from __future__ import annotations

ALL_RESOURCES = [
    "dashboard",
    "companies",
    "users",
    "profiles",
    "certificates",
    "documents",
    "query",
    "nfe",
    "nfce",
    "cte",
    "mdfe",
    "nfse",
    "dfe",
    "plugins",
    "policies",
    "jobs",
    "integrations",
    "api_clients",
    "webhooks",
    "reports",
    "audit",
]

TENANT_RESOURCE_PRESETS = {
    "complete": {
        "name": "Completo",
        "description": "Todos os recursos atuais do Hub Fiscal habilitados.",
        "resources": ALL_RESOURCES,
    },
    "fiscal_core": {
        "name": "Fiscal essencial",
        "description": "Cadastros, certificados, documentos e consultas fiscais.",
        "resources": [
            "dashboard",
            "companies",
            "users",
            "profiles",
            "certificates",
            "documents",
            "query",
            "nfe",
            "nfce",
            "cte",
            "mdfe",
            "nfse",
            "dfe",
            "jobs",
            "reports",
        ],
    },
    "documents_only": {
        "name": "Documentos e auditoria",
        "description": "Leitura, consulta, relatórios e auditoria, sem administração de integrações.",
        "resources": [
            "dashboard",
            "companies",
            "documents",
            "query",
            "nfe",
            "nfce",
            "cte",
            "mdfe",
            "nfse",
            "dfe",
            "reports",
            "audit",
        ],
    },
}

DEFAULT_ACCESS_PROFILES = [
    {
        "key": "tenant_owner",
        "name": "Proprietário",
        "description": "Controle integral do tenant.",
        "permissions": ["*"],
        "enabled_resources": ALL_RESOURCES,
        "system": True,
    },
    {
        "key": "tenant_admin",
        "name": "Administrador",
        "description": "Administração operacional completa do tenant.",
        "permissions": ["manage", "read", "write"],
        "enabled_resources": ALL_RESOURCES,
        "system": True,
    },
    {
        "key": "fiscal_manager",
        "name": "Gestor fiscal",
        "description": "Gerencia CNPJs, certificados, documentos, consultas e jobs.",
        "permissions": ["read", "write"],
        "enabled_resources": [
            "dashboard",
            "companies",
            "certificates",
            "documents",
            "query",
            "nfe",
            "nfce",
            "cte",
            "mdfe",
            "nfse",
            "dfe",
            "jobs",
            "reports",
            "audit",
        ],
        "system": True,
    },
    {
        "key": "fiscal_operator",
        "name": "Operador fiscal",
        "description": "Opera consultas, documentos e jobs sem administrar usuários ou integrações.",
        "permissions": ["read", "write"],
        "enabled_resources": [
            "dashboard",
            "companies",
            "certificates",
            "documents",
            "query",
            "nfe",
            "nfce",
            "cte",
            "mdfe",
            "nfse",
            "dfe",
            "jobs",
        ],
        "system": True,
    },
    {
        "key": "auditor",
        "name": "Auditor",
        "description": "Acesso de leitura a documentos, relatórios e auditoria.",
        "permissions": ["read"],
        "enabled_resources": ["dashboard", "companies", "documents", "query", "reports", "audit"],
        "system": True,
    },
]


def preset_resources(key: str | None) -> list[str]:
    preset = TENANT_RESOURCE_PRESETS.get(key or "complete", TENANT_RESOURCE_PRESETS["complete"])
    return list(preset["resources"])
